### ISSUE TITLE
Request for joining organisation.

### ISSUE THREAD

**Issue by dA505819** [TEDxP/Join_TEDxP#60]
@0x48piraj Hi there! I would love to be a part of TEDxP and will like o work for the betterment of society.
Kindly add me to the organisation.

**Comment by dA505819** [comment]
@0x48piraj Does the organization taking more members?

**Comment by 0x48piraj** [comment]
Already sent the invite. Check your email.

**Comment by dA505819** [comment]
Got it. Thanks!
