### ISSUE TITLE
Request to be added to the organization #62

### ISSUE THREAD

**Issue by ShreyasSubhedar** [TEDxP/Join_TEDxP#63]
Hi @0x48piraj,
I would love to be a part of TEDxP and it would be really great if I could get a chance to contribute for the betterment of the open source community .

Kindly add me to the organisation.

username: ShreyasSubhedar

 -Shreyas Subhedar
Associate Devops Enginner, Acquia

**Comment by 0x48piraj** [comment]
Sent the invite. Closing this issue.
