### ISSUE TITLE
Add Lalit Kumar

### ISSUE THREAD

**Issue by lalitmee** [TEDxP/Join_TEDxP#9]
Hey @0x48piraj , I would love to join this community :smile: . I am looking forward to have a great experience and learning. **I also want to help the community**. :hugs:

**Comment by 0x48piraj** [comment]
Rajendra Arora Just sent out the invitation!
Check your linked email account :wink:
Join our lobby too : https://gitter.im/TEDxHQ/Lobby :tada:
