### ISSUE TITLE
Would love to be a part of TEDxP | Join Organization as Member

### ISSUE THREAD

**Issue by aryashah2k** [TEDxP/Join_TEDxP#98]
Hi, I am Arya, and I would love to be a part of the TEDxP organization, understand its workflow and contribute to its projects.
Please invite me to join this organization and be a part of this awesome community!

**Comment by 0x48piraj** [comment]
Sent the invite. Be sure to publicize your organization membership.

**Comment by aryashah2k** [comment]
> Sent the invite. Be sure to publicize your organization membership.

Thank you for sending invite, I have accepted and publicised my membership!
